version: '3.9'

services:
  database:
    image: mysql:8.0.33
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: agave
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root